//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoapUtility.AttendanceServices {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CallContext", Namespace="http://schemas.microsoft.com/dynamics/2013/01/datacontracts")]
    [System.SerializableAttribute()]
    public partial class CallContext : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CompanyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LanguageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PartitionKeyField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Company {
            get {
                return this.CompanyField;
            }
            set {
                if ((object.ReferenceEquals(this.CompanyField, value) != true)) {
                    this.CompanyField = value;
                    this.RaisePropertyChanged("Company");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Language {
            get {
                return this.LanguageField;
            }
            set {
                if ((object.ReferenceEquals(this.LanguageField, value) != true)) {
                    this.LanguageField = value;
                    this.RaisePropertyChanged("Language");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MessageId {
            get {
                return this.MessageIdField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageIdField, value) != true)) {
                    this.MessageIdField = value;
                    this.RaisePropertyChanged("MessageId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PartitionKey {
            get {
                return this.PartitionKeyField;
            }
            set {
                if ((object.ReferenceEquals(this.PartitionKeyField, value) != true)) {
                    this.PartitionKeyField = value;
                    this.RaisePropertyChanged("PartitionKey");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Infolog", Namespace="http://schemas.microsoft.com/dynamics/2013/01/datacontracts")]
    [System.SerializableAttribute()]
    public partial class Infolog : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SoapUtility.AttendanceServices.InfologEntry[] EntriesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SoapUtility.AttendanceServices.InfologEntry[] Entries {
            get {
                return this.EntriesField;
            }
            set {
                if ((object.ReferenceEquals(this.EntriesField, value) != true)) {
                    this.EntriesField = value;
                    this.RaisePropertyChanged("Entries");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InfologEntry", Namespace="http://schemas.microsoft.com/dynamics/2013/01/datacontracts")]
    [System.SerializableAttribute()]
    public partial class InfologEntry : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SoapUtility.AttendanceServices.InfologType TypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SoapUtility.AttendanceServices.InfologType Type {
            get {
                return this.TypeField;
            }
            set {
                if ((this.TypeField.Equals(value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InfologType", Namespace="http://schemas.microsoft.com/dynamics/2013/01/datacontracts")]
    public enum InfologType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Info = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Warning = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Error = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Fault", Namespace="http://schemas.microsoft.com/dynamics/2013/01/datacontracts")]
    [System.SerializableAttribute()]
    public partial class Fault : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExceptionMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExceptionTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid RequestIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExceptionMessage {
            get {
                return this.ExceptionMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ExceptionMessageField, value) != true)) {
                    this.ExceptionMessageField = value;
                    this.RaisePropertyChanged("ExceptionMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExceptionType {
            get {
                return this.ExceptionTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.ExceptionTypeField, value) != true)) {
                    this.ExceptionTypeField = value;
                    this.RaisePropertyChanged("ExceptionType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid RequestId {
            get {
                return this.RequestIdField;
            }
            set {
                if ((this.RequestIdField.Equals(value) != true)) {
                    this.RequestIdField = value;
                    this.RaisePropertyChanged("RequestId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TimeCardContract", Namespace="http://schemas.datacontract.org/2004/07/Dynamics.AX.Application")]
    [System.SerializableAttribute()]
    public partial class TimeCardContract : SoapUtility.AttendanceServices.XppObjectBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime BeginCardTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EmployeeIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime EndCardTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MachineField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ShiftDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusReasonField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime BeginCardTime {
            get {
                return this.BeginCardTimeField;
            }
            set {
                if ((this.BeginCardTimeField.Equals(value) != true)) {
                    this.BeginCardTimeField = value;
                    this.RaisePropertyChanged("BeginCardTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EmployeeId {
            get {
                return this.EmployeeIdField;
            }
            set {
                if ((this.EmployeeIdField.Equals(value) != true)) {
                    this.EmployeeIdField = value;
                    this.RaisePropertyChanged("EmployeeId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime EndCardTime {
            get {
                return this.EndCardTimeField;
            }
            set {
                if ((this.EndCardTimeField.Equals(value) != true)) {
                    this.EndCardTimeField = value;
                    this.RaisePropertyChanged("EndCardTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Machine {
            get {
                return this.MachineField;
            }
            set {
                if ((object.ReferenceEquals(this.MachineField, value) != true)) {
                    this.MachineField = value;
                    this.RaisePropertyChanged("Machine");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ShiftDate {
            get {
                return this.ShiftDateField;
            }
            set {
                if ((this.ShiftDateField.Equals(value) != true)) {
                    this.ShiftDateField = value;
                    this.RaisePropertyChanged("ShiftDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StatusReason {
            get {
                return this.StatusReasonField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusReasonField, value) != true)) {
                    this.StatusReasonField = value;
                    this.RaisePropertyChanged("StatusReason");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProxyBase", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Dynamics.AX.KernelInterop")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SoapUtility.AttendanceServices.XppObjectBase))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SoapUtility.AttendanceServices.TimeCardSmallContract))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SoapUtility.AttendanceServices.TimeCardContract))]
    public partial class ProxyBase : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="XppObjectBase", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Dynamics.Ax.Xpp")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SoapUtility.AttendanceServices.TimeCardSmallContract))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SoapUtility.AttendanceServices.TimeCardContract))]
    public partial class XppObjectBase : SoapUtility.AttendanceServices.ProxyBase {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TimeCardSmallContract", Namespace="http://schemas.datacontract.org/2004/07/Dynamics.AX.Application")]
    [System.SerializableAttribute()]
    public partial class TimeCardSmallContract : SoapUtility.AttendanceServices.XppObjectBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CardTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EmployeeIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FaceImageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int JobClockInOutField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long LogCardIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MachineField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CardTime {
            get {
                return this.CardTimeField;
            }
            set {
                if ((this.CardTimeField.Equals(value) != true)) {
                    this.CardTimeField = value;
                    this.RaisePropertyChanged("CardTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EmployeeId {
            get {
                return this.EmployeeIdField;
            }
            set {
                if ((this.EmployeeIdField.Equals(value) != true)) {
                    this.EmployeeIdField = value;
                    this.RaisePropertyChanged("EmployeeId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FaceImage {
            get {
                return this.FaceImageField;
            }
            set {
                if ((object.ReferenceEquals(this.FaceImageField, value) != true)) {
                    this.FaceImageField = value;
                    this.RaisePropertyChanged("FaceImage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int JobClockInOut {
            get {
                return this.JobClockInOutField;
            }
            set {
                if ((this.JobClockInOutField.Equals(value) != true)) {
                    this.JobClockInOutField = value;
                    this.RaisePropertyChanged("JobClockInOut");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long LogCardId {
            get {
                return this.LogCardIdField;
            }
            set {
                if ((this.LogCardIdField.Equals(value) != true)) {
                    this.LogCardIdField = value;
                    this.RaisePropertyChanged("LogCardId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Machine {
            get {
                return this.MachineField;
            }
            set {
                if ((object.ReferenceEquals(this.MachineField, value) != true)) {
                    this.MachineField = value;
                    this.RaisePropertyChanged("Machine");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://tempuri.org", ConfigurationName="AttendanceServices.EmpTimeCardService")]
    public interface EmpTimeCardService {
        
        // CODEGEN: Generating message contract since message applyLeaveTransaction has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EmpTimeCardService/applyLeaveTransaction", ReplyAction="http://tempuri.org/EmpTimeCardService/applyLeaveTransactionResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SoapUtility.AttendanceServices.Fault), Action="http://tempuri.org/EmpTimeCardService/Fault", Name="Fault", Namespace="http://schemas.microsoft.com/dynamics/2013/01/datacontracts")]
        SoapUtility.AttendanceServices.applyLeaveTransactionResponse applyLeaveTransaction(SoapUtility.AttendanceServices.applyLeaveTransaction request);
        
        // CODEGEN: Generating message contract since message CreateAttendance has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EmpTimeCardService/CreateAttendance", ReplyAction="http://tempuri.org/EmpTimeCardService/CreateAttendanceResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SoapUtility.AttendanceServices.Fault), Action="http://tempuri.org/EmpTimeCardService/Fault", Name="Fault", Namespace="http://schemas.microsoft.com/dynamics/2013/01/datacontracts")]
        SoapUtility.AttendanceServices.CreateAttendanceResponse CreateAttendance(SoapUtility.AttendanceServices.CreateAttendance request);
        
        // CODEGEN: Generating message contract since message GetLastMachineLogIds has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EmpTimeCardService/GetLastMachineLogIds", ReplyAction="http://tempuri.org/EmpTimeCardService/GetLastMachineLogIdsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SoapUtility.AttendanceServices.Fault), Action="http://tempuri.org/EmpTimeCardService/Fault", Name="Fault", Namespace="http://schemas.microsoft.com/dynamics/2013/01/datacontracts")]
        SoapUtility.AttendanceServices.GetLastMachineLogIdsResponse GetLastMachineLogIds(SoapUtility.AttendanceServices.GetLastMachineLogIds request);
        
        // CODEGEN: Generating message contract since message getLastSwipeId has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EmpTimeCardService/getLastSwipeId", ReplyAction="http://tempuri.org/EmpTimeCardService/getLastSwipeIdResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SoapUtility.AttendanceServices.Fault), Action="http://tempuri.org/EmpTimeCardService/Fault", Name="Fault", Namespace="http://schemas.microsoft.com/dynamics/2013/01/datacontracts")]
        SoapUtility.AttendanceServices.getLastSwipeIdResponse getLastSwipeId(SoapUtility.AttendanceServices.getLastSwipeId request);
        
        // CODEGEN: Generating message contract since message SaveRawAttendance has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EmpTimeCardService/SaveRawAttendance", ReplyAction="http://tempuri.org/EmpTimeCardService/SaveRawAttendanceResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SoapUtility.AttendanceServices.Fault), Action="http://tempuri.org/EmpTimeCardService/Fault", Name="Fault", Namespace="http://schemas.microsoft.com/dynamics/2013/01/datacontracts")]
        SoapUtility.AttendanceServices.SaveRawAttendanceResponse SaveRawAttendance(SoapUtility.AttendanceServices.SaveRawAttendance request);
        
        // CODEGEN: Generating message contract since message WorkerInOutRegistration has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EmpTimeCardService/WorkerInOutRegistration", ReplyAction="http://tempuri.org/EmpTimeCardService/WorkerInOutRegistrationResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SoapUtility.AttendanceServices.Fault), Action="http://tempuri.org/EmpTimeCardService/Fault", Name="Fault", Namespace="http://schemas.microsoft.com/dynamics/2013/01/datacontracts")]
        SoapUtility.AttendanceServices.WorkerInOutRegistrationResponse WorkerInOutRegistration(SoapUtility.AttendanceServices.WorkerInOutRegistration request);
        
        // CODEGEN: Generating message contract since message WorkerInOutRegistrationForDay has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EmpTimeCardService/WorkerInOutRegistrationForDay", ReplyAction="http://tempuri.org/EmpTimeCardService/WorkerInOutRegistrationForDayResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SoapUtility.AttendanceServices.Fault), Action="http://tempuri.org/EmpTimeCardService/Fault", Name="Fault", Namespace="http://schemas.microsoft.com/dynamics/2013/01/datacontracts")]
        SoapUtility.AttendanceServices.WorkerInOutRegistrationForDayResponse WorkerInOutRegistrationForDay(SoapUtility.AttendanceServices.WorkerInOutRegistrationForDay request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="applyLeaveTransaction", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class applyLeaveTransaction {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.microsoft.com/dynamics/2013/01/datacontracts")]
        public SoapUtility.AttendanceServices.CallContext CallContext;
        
        public applyLeaveTransaction() {
        }
        
        public applyLeaveTransaction(SoapUtility.AttendanceServices.CallContext CallContext) {
            this.CallContext = CallContext;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="applyLeaveTransactionResponse", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class applyLeaveTransactionResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.microsoft.com/dynamics/2013/01/datacontracts")]
        public SoapUtility.AttendanceServices.Infolog Infolog;
        
        public applyLeaveTransactionResponse() {
        }
        
        public applyLeaveTransactionResponse(SoapUtility.AttendanceServices.Infolog Infolog) {
            this.Infolog = Infolog;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateAttendance", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class CreateAttendance {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.microsoft.com/dynamics/2013/01/datacontracts")]
        public SoapUtility.AttendanceServices.CallContext CallContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public SoapUtility.AttendanceServices.TimeCardContract[] lines;
        
        public CreateAttendance() {
        }
        
        public CreateAttendance(SoapUtility.AttendanceServices.CallContext CallContext, SoapUtility.AttendanceServices.TimeCardContract[] lines) {
            this.CallContext = CallContext;
            this.lines = lines;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateAttendanceResponse", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class CreateAttendanceResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.microsoft.com/dynamics/2013/01/datacontracts")]
        public SoapUtility.AttendanceServices.Infolog Infolog;
        
        public CreateAttendanceResponse() {
        }
        
        public CreateAttendanceResponse(SoapUtility.AttendanceServices.Infolog Infolog) {
            this.Infolog = Infolog;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetLastMachineLogIds", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class GetLastMachineLogIds {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.microsoft.com/dynamics/2013/01/datacontracts")]
        public SoapUtility.AttendanceServices.CallContext CallContext;
        
        public GetLastMachineLogIds() {
        }
        
        public GetLastMachineLogIds(SoapUtility.AttendanceServices.CallContext CallContext) {
            this.CallContext = CallContext;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetLastMachineLogIdsResponse", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class GetLastMachineLogIdsResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.microsoft.com/dynamics/2013/01/datacontracts")]
        public SoapUtility.AttendanceServices.Infolog Infolog;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public SoapUtility.AttendanceServices.TimeCardSmallContract[] result;
        
        public GetLastMachineLogIdsResponse() {
        }
        
        public GetLastMachineLogIdsResponse(SoapUtility.AttendanceServices.Infolog Infolog, SoapUtility.AttendanceServices.TimeCardSmallContract[] result) {
            this.Infolog = Infolog;
            this.result = result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getLastSwipeId", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class getLastSwipeId {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.microsoft.com/dynamics/2013/01/datacontracts")]
        public SoapUtility.AttendanceServices.CallContext CallContext;
        
        public getLastSwipeId() {
        }
        
        public getLastSwipeId(SoapUtility.AttendanceServices.CallContext CallContext) {
            this.CallContext = CallContext;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getLastSwipeIdResponse", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class getLastSwipeIdResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.microsoft.com/dynamics/2013/01/datacontracts")]
        public SoapUtility.AttendanceServices.Infolog Infolog;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public long result;
        
        public getLastSwipeIdResponse() {
        }
        
        public getLastSwipeIdResponse(SoapUtility.AttendanceServices.Infolog Infolog, long result) {
            this.Infolog = Infolog;
            this.result = result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SaveRawAttendance", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class SaveRawAttendance {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.microsoft.com/dynamics/2013/01/datacontracts")]
        public SoapUtility.AttendanceServices.CallContext CallContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public SoapUtility.AttendanceServices.TimeCardSmallContract[] lines;
        
        public SaveRawAttendance() {
        }
        
        public SaveRawAttendance(SoapUtility.AttendanceServices.CallContext CallContext, SoapUtility.AttendanceServices.TimeCardSmallContract[] lines) {
            this.CallContext = CallContext;
            this.lines = lines;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SaveRawAttendanceResponse", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class SaveRawAttendanceResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.microsoft.com/dynamics/2013/01/datacontracts")]
        public SoapUtility.AttendanceServices.Infolog Infolog;
        
        public SaveRawAttendanceResponse() {
        }
        
        public SaveRawAttendanceResponse(SoapUtility.AttendanceServices.Infolog Infolog) {
            this.Infolog = Infolog;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="WorkerInOutRegistration", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class WorkerInOutRegistration {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.microsoft.com/dynamics/2013/01/datacontracts")]
        public SoapUtility.AttendanceServices.CallContext CallContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public SoapUtility.AttendanceServices.TimeCardSmallContract[] lines;
        
        public WorkerInOutRegistration() {
        }
        
        public WorkerInOutRegistration(SoapUtility.AttendanceServices.CallContext CallContext, SoapUtility.AttendanceServices.TimeCardSmallContract[] lines) {
            this.CallContext = CallContext;
            this.lines = lines;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="WorkerInOutRegistrationResponse", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class WorkerInOutRegistrationResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.microsoft.com/dynamics/2013/01/datacontracts")]
        public SoapUtility.AttendanceServices.Infolog Infolog;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public string result;
        
        public WorkerInOutRegistrationResponse() {
        }
        
        public WorkerInOutRegistrationResponse(SoapUtility.AttendanceServices.Infolog Infolog, string result) {
            this.Infolog = Infolog;
            this.result = result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="WorkerInOutRegistrationForDay", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class WorkerInOutRegistrationForDay {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.microsoft.com/dynamics/2013/01/datacontracts")]
        public SoapUtility.AttendanceServices.CallContext CallContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public System.DateTime endDate;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=1)]
        public System.DateTime startDate;
        
        public WorkerInOutRegistrationForDay() {
        }
        
        public WorkerInOutRegistrationForDay(SoapUtility.AttendanceServices.CallContext CallContext, System.DateTime endDate, System.DateTime startDate) {
            this.CallContext = CallContext;
            this.endDate = endDate;
            this.startDate = startDate;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="WorkerInOutRegistrationForDayResponse", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class WorkerInOutRegistrationForDayResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.microsoft.com/dynamics/2013/01/datacontracts")]
        public SoapUtility.AttendanceServices.Infolog Infolog;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public string result;
        
        public WorkerInOutRegistrationForDayResponse() {
        }
        
        public WorkerInOutRegistrationForDayResponse(SoapUtility.AttendanceServices.Infolog Infolog, string result) {
            this.Infolog = Infolog;
            this.result = result;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface EmpTimeCardServiceChannel : SoapUtility.AttendanceServices.EmpTimeCardService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EmpTimeCardServiceClient : System.ServiceModel.ClientBase<SoapUtility.AttendanceServices.EmpTimeCardService>, SoapUtility.AttendanceServices.EmpTimeCardService {
        
        public EmpTimeCardServiceClient() {
        }
        
        public EmpTimeCardServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EmpTimeCardServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EmpTimeCardServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EmpTimeCardServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoapUtility.AttendanceServices.applyLeaveTransactionResponse SoapUtility.AttendanceServices.EmpTimeCardService.applyLeaveTransaction(SoapUtility.AttendanceServices.applyLeaveTransaction request) {
            return base.Channel.applyLeaveTransaction(request);
        }
        
        public SoapUtility.AttendanceServices.Infolog applyLeaveTransaction(SoapUtility.AttendanceServices.CallContext CallContext) {
            SoapUtility.AttendanceServices.applyLeaveTransaction inValue = new SoapUtility.AttendanceServices.applyLeaveTransaction();
            inValue.CallContext = CallContext;
            SoapUtility.AttendanceServices.applyLeaveTransactionResponse retVal = ((SoapUtility.AttendanceServices.EmpTimeCardService)(this)).applyLeaveTransaction(inValue);
            return retVal.Infolog;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoapUtility.AttendanceServices.CreateAttendanceResponse SoapUtility.AttendanceServices.EmpTimeCardService.CreateAttendance(SoapUtility.AttendanceServices.CreateAttendance request) {
            return base.Channel.CreateAttendance(request);
        }
        
        public SoapUtility.AttendanceServices.Infolog CreateAttendance(SoapUtility.AttendanceServices.CallContext CallContext, SoapUtility.AttendanceServices.TimeCardContract[] lines) {
            SoapUtility.AttendanceServices.CreateAttendance inValue = new SoapUtility.AttendanceServices.CreateAttendance();
            inValue.CallContext = CallContext;
            inValue.lines = lines;
            SoapUtility.AttendanceServices.CreateAttendanceResponse retVal = ((SoapUtility.AttendanceServices.EmpTimeCardService)(this)).CreateAttendance(inValue);
            return retVal.Infolog;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoapUtility.AttendanceServices.GetLastMachineLogIdsResponse SoapUtility.AttendanceServices.EmpTimeCardService.GetLastMachineLogIds(SoapUtility.AttendanceServices.GetLastMachineLogIds request) {
            return base.Channel.GetLastMachineLogIds(request);
        }
        
        public SoapUtility.AttendanceServices.Infolog GetLastMachineLogIds(SoapUtility.AttendanceServices.CallContext CallContext, out SoapUtility.AttendanceServices.TimeCardSmallContract[] result) {
            SoapUtility.AttendanceServices.GetLastMachineLogIds inValue = new SoapUtility.AttendanceServices.GetLastMachineLogIds();
            inValue.CallContext = CallContext;
            SoapUtility.AttendanceServices.GetLastMachineLogIdsResponse retVal = ((SoapUtility.AttendanceServices.EmpTimeCardService)(this)).GetLastMachineLogIds(inValue);
            result = retVal.result;
            return retVal.Infolog;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoapUtility.AttendanceServices.getLastSwipeIdResponse SoapUtility.AttendanceServices.EmpTimeCardService.getLastSwipeId(SoapUtility.AttendanceServices.getLastSwipeId request) {
            return base.Channel.getLastSwipeId(request);
        }
        
        public SoapUtility.AttendanceServices.Infolog getLastSwipeId(SoapUtility.AttendanceServices.CallContext CallContext, out long result) {
            SoapUtility.AttendanceServices.getLastSwipeId inValue = new SoapUtility.AttendanceServices.getLastSwipeId();
            inValue.CallContext = CallContext;
            SoapUtility.AttendanceServices.getLastSwipeIdResponse retVal = ((SoapUtility.AttendanceServices.EmpTimeCardService)(this)).getLastSwipeId(inValue);
            result = retVal.result;
            return retVal.Infolog;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoapUtility.AttendanceServices.SaveRawAttendanceResponse SoapUtility.AttendanceServices.EmpTimeCardService.SaveRawAttendance(SoapUtility.AttendanceServices.SaveRawAttendance request) {
            return base.Channel.SaveRawAttendance(request);
        }
        
        public SoapUtility.AttendanceServices.Infolog SaveRawAttendance(SoapUtility.AttendanceServices.CallContext CallContext, SoapUtility.AttendanceServices.TimeCardSmallContract[] lines) {
            SoapUtility.AttendanceServices.SaveRawAttendance inValue = new SoapUtility.AttendanceServices.SaveRawAttendance();
            inValue.CallContext = CallContext;
            inValue.lines = lines;
            SoapUtility.AttendanceServices.SaveRawAttendanceResponse retVal = ((SoapUtility.AttendanceServices.EmpTimeCardService)(this)).SaveRawAttendance(inValue);
            return retVal.Infolog;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoapUtility.AttendanceServices.WorkerInOutRegistrationResponse SoapUtility.AttendanceServices.EmpTimeCardService.WorkerInOutRegistration(SoapUtility.AttendanceServices.WorkerInOutRegistration request) {
            return base.Channel.WorkerInOutRegistration(request);
        }
        
        public SoapUtility.AttendanceServices.Infolog WorkerInOutRegistration(SoapUtility.AttendanceServices.CallContext CallContext, SoapUtility.AttendanceServices.TimeCardSmallContract[] lines, out string result) {
            SoapUtility.AttendanceServices.WorkerInOutRegistration inValue = new SoapUtility.AttendanceServices.WorkerInOutRegistration();
            inValue.CallContext = CallContext;
            inValue.lines = lines;
            SoapUtility.AttendanceServices.WorkerInOutRegistrationResponse retVal = ((SoapUtility.AttendanceServices.EmpTimeCardService)(this)).WorkerInOutRegistration(inValue);
            result = retVal.result;
            return retVal.Infolog;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoapUtility.AttendanceServices.WorkerInOutRegistrationForDayResponse SoapUtility.AttendanceServices.EmpTimeCardService.WorkerInOutRegistrationForDay(SoapUtility.AttendanceServices.WorkerInOutRegistrationForDay request) {
            return base.Channel.WorkerInOutRegistrationForDay(request);
        }
        
        public SoapUtility.AttendanceServices.Infolog WorkerInOutRegistrationForDay(SoapUtility.AttendanceServices.CallContext CallContext, System.DateTime endDate, System.DateTime startDate, out string result) {
            SoapUtility.AttendanceServices.WorkerInOutRegistrationForDay inValue = new SoapUtility.AttendanceServices.WorkerInOutRegistrationForDay();
            inValue.CallContext = CallContext;
            inValue.endDate = endDate;
            inValue.startDate = startDate;
            SoapUtility.AttendanceServices.WorkerInOutRegistrationForDayResponse retVal = ((SoapUtility.AttendanceServices.EmpTimeCardService)(this)).WorkerInOutRegistrationForDay(inValue);
            result = retVal.result;
            return retVal.Infolog;
        }
    }
}
